- name: Enable CRB repo for RHEL9 variation.
  command: dnf config-manager --set-enabled crb
  when:
    - ansible_distribution_major_version == "9"
    - (ansible_distribution == "AlmaLinux") or (ansible_distribution == "Rocky") or (ansible_distribution == "CentOS")
- name: checking yum repo
  stat:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
  register: stat_yum_repo
- name: Install PostgreSQL repository
  yum: 
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
  when: not stat_yum_repo.stat.exists
- name: Install python2-passlib for hpasswd 
  yum:
    name:  python2-passlib
    state: present
- name: Install psycopg2 for postgresql control. 
  package:
    name:  python-psycopg2
    state: present
- name: "Install PostgreSQL {{ psql_version }} Server"
  package: 
    name: "postgresql{{ psql_version }}-server"
    state: present
- name: "Checking the DB is ready."
  stat:
    path: "/var/lib/pgsql/{{ psql_version }}/data"
  register: psql_data
  notify: configure DB
- name: "Initilizing PostgreSQL DB"
  command: /usr/pgsql-{{ psql_version }}/bin/postgresql-{{ psql_version }}-setup initdb
  when: not psql_data.stat.exists  
- copy: 
    dest: "/var/lib/pgsql/{{ psql_version }}/data/pg_hba.conf"
    owner: postgres
    group: postgres
    content: "local   all             all                                     trust\n
host    all             all             127.0.0.1/32            trust\n
host    all             all             ::1/128                 trust\n
"  
- copy:
    dest: /etc/dcache/ban.conf
    owner: dcache
    group: dcache
    content: ""
    mode: "0644" 
- copy: 
    dest: /etc/dcache/gplazma.conf
    owner: dcache
    group: dcache
    mode: "0644"
    content:  "auth     sufficient  htpasswd\n
map      sufficient  multimap\n
account  requisite   banfile\n
session  requisite   authzdb\n
"
- community.general.htpasswd:
    path: /etc/dcache/htpasswd
    name: vagrant
    password: vagrant
    owner: dcache
    group: dcache
    mode: 0640
- community.general.htpasswd:
    path: /etc/dcache/htpasswd
    name: admin
    password: admin
    owner: dcache
    group: dcache
    mode: 0640
- name: create /etc/grid-security directory
  file:
    path: /etc/grid-security
    state: directory
    owner: root
    group: root
- copy:
    dest: /etc/grid-security/storage-authzdb
    owner: dcache
    group: dcache
    content: "version 2.1\n

authorize vagrant read-write 1000 1000 /home/vagrant /\n
authorize admin read-write 0 0 / /\n
"
- copy:
    dest: /etc/dcache/multi-mapfile
    owner: dcache
    group: dcache
    content: "username:vagrant uid:1000 gid:1000,true\n
username:admin uid:0 gid:0,true"
- copy:
    dest: /etc/dcache/dcache.conf
    owner: dcache
    group: dcache
    mode: "0644"
    content: "dcache.layout=nonpool\n"
- template: 
    src: nonpool.conf.j2
    dest: /etc/dcache/layouts/nonpool.conf
    owner: dcache
    group: dcache
    mode: "0644"
- name: Restart dcache 
  command: dcache restart

- name: Install XRootD server
  package: 
    name: xrootd-server
    state: latest
