---
# handlers file for geonmo.dcache
- name: configure DB                                                                                                                                                                                           
  include_tasks: tasks/config_db.yml
- name: restart db
  service:
    name: postgresql-{{ psql_version }}
    state: restarted
- name: dcache db update
  command: /usr/bin/dcache database update
- name: restart dcache
  service: 
    name: dcache.target
    state: restarted
